force-app/main/default/objects/Star__c/Star__c.object-meta.xml
<CustomObject>
    <label>Star</label>
    <nameField>
        <label>Star Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star__c/fields/NumberForks__c.field-meta.xml
<CustomField>
    <fullName>NumberForks__c</fullName>
    <defaultValue>0</defaultValue>
    <description>number of forks</description>
    <label>Number of Forks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Star__c/fields/NumberStars__c.field-meta.xml
<CustomField>
    <fullName>NumberStars__c</fullName>
    <defaultValue>0</defaultValue>
    <description>number of stars</description>
    <label>Number of Stars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BetchStarTest.cls
@isTest
private class BetchStarTest {
    @isTest public static void upsertTest() {
        Star__c  star = new Star__c();
        star.Login__c = 'test';
        star.Name = 'test';
        star.ExternalID__c = '121395510';
        star.NumberForks__c = 233;
        star.NumberStars__c = 455;
        insert star;

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpMock());

        Database.executeBatch(new BetchStar(), 10);

        Test.stopTest();
    }
}